---
# tasks file for ansible-rundeck
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: users.yml

- import_tasks: config_rundeck.yml
  when: rundeck_config_rundeck

- import_tasks: services.yml
