---
- name: users | creating rundeck ssh folder
  file:
    path: "{{ rundeck_framework_ssh_keypath }}"
    state: directory
    owner: "{{ rundeck_framework_ssh_user }}"
    group: "{{ rundeck_framework_ssh_user }}"
    mode: 0700
  become: true

- name: users | generating rundeck ssh key
  user:
    name: "{{ rundeck_framework_ssh_user }}"
    generate_ssh_key: "{{ rundeck_ssh_generate_key }}"
    ssh_key_file: "{{ rundeck_framework_ssh_keypath_file }}"
  become: true

- name: users | downloading rundeck users ssh public key
  fetch:
    src: "{{ rundeck_framework_ssh_keypath_file + '.pub' }}"
    dest: "{{ rundeck_ssh_keydir + '/' + rundeck_framework_ssh_user + '@' + ansible_hostname + '.pub' }}"
    flat: yes
  become: true
  when: rundeck_ssh_generate_key
