---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu1804
    image: ubuntu:18.04
    exposed_ports:
      - 4440
    published_ports:
      - 0.0.0.0:4440:4440/tcp
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ["306"]
verifier:
  name: testinfra
  lint:
    name: flake8
